### ISSUE TITLE
[Docker] Can't connect to Kafka Server with container's name in docker network

### ISSUE THREAD

**Issue by dinopuguh** [IBM/sarama#1683]
### Versions

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.26.1 | v2.4.1 | v1.14.1 |

##### Configuration

This is my application called as `my-app`:
``` go

brokers := fmt.Sprintf("%v:%v", os.Getenv("KAFKA_HOST"), os.Getenv("KAFKA_PORT"))
group := os.Getenv("CONSUMER_GROUP")
topics := os.Getenv("TOPICS")
version := os.Getenv("KAFKA_VERSION")

kafkaConfig := sarama.NewConfig()
kafkaConfig.Consumer.Offsets.Initial = sarama.OffsetOldest
kafkaConfig.Consumer.Group.Rebalance.Strategy = sarama.BalanceStrategyRoundRobin
kafkaConfig.Version = version

if username != "" && password != "" {
	kafkaConfig.Net.SASL.Enable = true
	kafkaConfig.Net.SASL.User = username
	kafkaConfig.Net.SASL.Password = password
}

client, err := sarama.NewConsumerGroup(strings.Split(brokers, ","), group, kafkaConfig)
if err != nil {
	log.Panicf("Error creating consumer group client: %v", err)
}
```
`docker-compose.yml` file:
```
version: "3.7"

services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.6
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1
      ZOOKEEPER_SERVER_ID: 1
    volumes:
      - /zookeeper/data:/data
      - /zookeeper/log:/datalog
    networks:
      - my-network
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.4.1
    ports:
      - 9093:9093
    expose:
      - 9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_DIRS: /logs
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /kafka/data:/logs
      - /kafka/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - my-network
  my-app:
    container_name: my-app
    image: my-app:3.0
    ports:
      - 9001:9090
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      CONSUMER_GROUP: my-group
      TOPICS: reviews
      KAFKA_VERSION: 2.4.1
    networks:
      - my-network

networks:
  my-network:
    name: my-network

```

##### Logs

When I set `KAFKA_HOST:kafka` in `docker-compose.yml`:
<details><summary>logs: CLICK ME</summary>
<p>

```
Error creating consumer group client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```
</details>

##### Problem Description

Sarama can't create a consumer group with that configuration. But, if I set `KAFKA_HOST` with Kafka container's IP Address, it works very well. So, I think sarama cannot accept brokers that defined with the hostname.

please for your help, thank you.
