### ISSUE TITLE
sarama.CreateAclsRequest: Ignoring TextMarshaler & TextUnmarshaler for members

### ISSUE THREAD

**Issue by Go-Giter** [IBM/sarama#2888]
##### Description

I have a need to marshal / unmarshal the contents of an `&sarama.CreateAclsRequest`. Unfortunately when marshaling a populated struct the fields `permissiontype`, `resourcetype`, `resourcepatterntype`, & `operation` come out as integers despite implementing [encoding.TextMarshaler](https://github.com/IBM/sarama/blob/main/acl_types.go#L59-L61) & [encoding.TextUnmarshaler](https://github.com/IBM/sarama/blob/main/acl_types.go#L64-L88). The integer values aren't very meaningful to a human. 

##### Versions

| Sarama    | Kafka | Go  |
| `v1.43.2` | `N/A`  |  `1.22.2` |

##### Configuration

```go
package main

import (
	"fmt"

	"github.com/IBM/sarama"

	"gopkg.in/yaml.v3"
)

func main() {
	car := []*sarama.CreateAclsRequest{
		{
			Version: int16(3),
			AclCreations: []*sarama.AclCreation{
				{
					Resource: sarama.Resource{
						ResourceType:        sarama.AclResourceTopic,
						ResourceName:        "test.topic",
						ResourcePatternType: sarama.AclPatternLiteral,
					},
					Acl: sarama.Acl{
						Principal:      "test-user",
						Host:           "test-host",
						Operation:      sarama.AclOperationRead,
						PermissionType: sarama.AclPermissionAllow,
					},
				},
			},
		},
	}

	b, err := yaml.Marshal(car)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s", b)
}
```

##### Logs

```
- version: 3
  aclcreations:
    - resource:
        resourcetype: 2
        resourcename: test.topic
        resourcepatterntype: 3
      acl:
        principal: test-user
        host: test-host
        operation: 3
        permissiontype: 3
```

##### Additional Context

The receiver types on the encoding.TextMarshal and encoding.Unmarshal interfaces are pointers, while the types within the aforementioned struct are values. Also relevant is this [go-yaml](https://github.com/go-yaml/yaml/issues/959) issue, though IMO this isn't really a bug, but just the way Go works. 

Perhaps I am missing the actual issue, but should we convert the struct to contain pointers to these integer types?
